### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by ghost** [rsrbk/SmileToUnlock#2]
Hello sir, thanks you for your library ,  any news for the others iphones ?

**Comment by rsrbk** [comment]
Hello,
The library should be working on newer iPhones as well, are you experiencing any problem?

**Comment by ghost** [comment]
Hey , in the doc its saying it will work only with iPhone X device..

**Comment by rsrbk** [comment]
Yeah, I think at the time I created this library there was only iPhone X :) 
I'll update the description.
